import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./auth/hooks/authContext";
import { NavBar } from "@/components/nav/navigation";
import { Socket } from "socket.io-client";
import { SocketProvider } from "./hook/socketContext";
import { Toaster } from "@/components/ui/toaster"
import { Suspense } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<Suspense fallback={<div>Loading...</div>}>
        <SocketProvider >
          <AuthProvider>
            {/* <NavBar> */}
              {children}
              <Toaster />
            {/* </NavBar> */}
          </AuthProvider>
        </SocketProvider>
        </Suspense>
      </body>
    </html>
  );
}
